stages:
  - sast
  - tag
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH

before_script:
  - set -e

sast:
  stage: sast
include:
- template: Security/SAST.gitlab-ci.yml

Build Release:
  stage: deploy
  image: docker:stable
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
  services:
    - docker:stable-dind
  script:
    - docker pull $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} || true
    - docker build --cache-from $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} --build-arg VERSION="$CI_COMMIT_REF_NAME" --tag $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} --tag index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG} .
    - docker build --cache-from $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG}-nochrome --build-arg VERSION="$CI_COMMIT_REF_NAME" --tag $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG}-nochrome --tag index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}-nochrome -f ./nochrome.Dockerfile .
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG}
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG}-nochrome
    - docker push index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}
    - docker push index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}-nochrome

Update Version:
  image: node:16
  stage: tag
  only:
    - tags
  artifacts:
    expire_in: 1 day
    paths:
      - package-lock.json
      - package.json
  script:
    - npm --no-git-tag-version version $CI_COMMIT_TAG

Compile GUI:
  image: node:16
  stage: build
  only:
    - tags
    - master
  artifacts:
    expire_in: 1 day
    paths:
      - package-lock.json
      - package.json
      - public
  script:
    - NODE_ENV=build && npm ci && NODE_ENV=production
    - npm run compile-gui

Build Production:
  stage: deploy
  image: docker:stable
  only:
    - tags
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
  services:
    - docker:stable-dind
  script:
    - docker pull $CONTAINER_IMAGE:stable || true
    - docker build --cache-from $CONTAINER_IMAGE:stable --build-arg VERSION="$CI_COMMIT_TAG" --tag $CONTAINER_IMAGE:${CI_COMMIT_TAG} --tag $CONTAINER_IMAGE:stable --tag index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_TAG} --tag index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:stable .
    - docker build --cache-from $CONTAINER_IMAGE:stable-nochrome --build-arg VERSION="$CI_COMMIT_TAG" --tag $CONTAINER_IMAGE:${CI_COMMIT_TAG}-nochrome --tag $CONTAINER_IMAGE:stable-nochrome --tag index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_TAG}-nochrome --tag index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:stable-nochrome -f ./nochrome.Dockerfile .
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_TAG}
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_TAG}-nochrome
    - docker push $CONTAINER_IMAGE:stable
    - docker push $CONTAINER_IMAGE:stable-nochrome
    - docker push index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_TAG}
    - docker push index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:${CI_COMMIT_TAG}-nochrome
    - docker push index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:stable
    - docker push index.$DOCKER_REGISTRY/$DOCKER_USER/$CI_PROJECT_NAME:stable-nochrome
